API_KEY="liteapi_api_key"

#Step 1 Hotel Search

import requests

headers = {
    "X-API-Key": API_KEY
}

r = requests.get(
    "https://api.liteapi.travel/v3.0/data/hotels",
    headers=headers,
    params={
        "cityName":"Goa",
        "countryCode":"IN",
        "limit":20
    }
)

hotels = r.json()["data"]
hotels

# OUTPUT:
# [{'id': 'lp656ee431',
#   'primaryHotelId': None,
#   'name': 'Alaya Stays 1 BHK with Balcony & Pool - Veera Marina',
#   'hotelDescription': '<p><strong>Luxurious Amenities</strong><br>Enjoy a comfortable stay with air-conditioned rooms, a fully equipped kitchen, and a balcony overlooking the pool.</p><p><strong>Convenient Services</strong><br>Take advantage of private parking, free WiFi, airport transfers, and car rental options for easy exploration of Goa.</p><p><strong>Ideal Location</strong><br>Located just 1.4 km from Candolim Beach, with Calangute Beach and Chapora Fort a short drive away. Book now for a memorable stay at Alaya Stays 1 BHK with Balcony &amp; Pool - Veera Marina.</p>',
#   'hotelTypeId': 201,
#   'chain': 'Not Available',
#   'currency': '',
#   'country': 'in',
#   'city': 'Goa',
#   'latitude': 15.520296,
#   'longitude': 73.773251,
#   'address': 'Solace, Candolim, Goa 403515',
#   'zip': '',
#   'main_photo': 'https://static.cupid.travel/hotels/600989321.jpg',
#   'thumbnail': 'https://static.cupid.travel/hotels/thumbnail/600989321.jpg',
#   'stars': 4,
#   'rating': 10,
#   'reviewCount': 16,
#   'facilityIds': [47,
#    107,
#    2,
#    46,
#    16,
#    109,
#    301,
#    28,
#    14,
#    72,
#    48,
#    17,
#    75,
#    55,
#    54,
#    161,
#    104,
#    127,
#    158,
#    184,
#    140,
#    170,
#    159,
#    173,
#    222,
#    203,
#    210,
#    209,
#    205,
#    241,
#    304,
#    455,
#    450,
#    451,
#    449,
#    462,
#    457,
#    461,
#    425,
#    459,
#    467,
#    465,
#    456,
#    452,
#    453,
#    454,
#    424,
#    423,
#    458,
#    488,
#    418,
#    485,
#    487,
#    484],
#   'accessibilityAttributes': {'attributes': None,
#    'showerChair': None,
#    'entranceType': None,
#    'petFriendly': '',
#    'rampAngle': 0,
#    'rampLength': 0,
#    'entranceDoorWidth': 0,
#    'roomMaxGuestsNumber': 0,
#    'distanceFromTheElevatorToTheAccessibleRoom': 0},
#   'deletedAt': None},
#  {'id': 'lp657c9251',
#   'primaryHotelId': None,
#   'name': 'Georgies wooden homes stay',
#   'hotelDescription': '<p><strong>Luxurious Wooden Homes</strong><br>Experience spacious air-conditioned accommodation with a balcony and free WiFi, just a short distance from the stunning beaches of Goa.</p><p><strong>Indoor Pool with Scenic Views</strong><br>Relax in our indoor pool with pool views, perfect for unwinding after a day of exploring the nearby beaches.</p><p><strong>Authentic Indian Dining Experience</strong><br>Indulge in delicious Indian cuisine at our family-friendly restaurant, open for dinner, lunch, and brunch, providing a true taste of Goa.</p><p>Book your stay at Georgies Wooden Homes now to enjoy a relaxing getaway in the heart of Goa.</p>',
#   'hotelTypeId': 208,
#   'chain': 'Not Available',
#   'currency': '',
#   'country': 'in',
#   'city': 'Goa',
#   'latitude': 15.542777,
#   'longitude': 73.763178,
#   'address': 'House no 2/174/B,near sia signature hotel,Naika Vaddo,Calangute,Goa. 403516 House no 2/174/B',
#   'zip': '',
#   'main_photo': 'https://static.cupid.travel/hotels/608574685.jpg',
#   'thumbnail': 'https://static.cupid.travel/hotels/thumbnail/608574685.jpg',
#   'stars': 0,
#   'rating': 9.3,
#   'reviewCount': 70,
#   'facilityIds': [47,
#    107,
#    2,
#    46,
#    16,
#    109,
#    301,
#    3,
#    28,
#    14,
#    7,
#    59,
#    108,
#    161,
#    103,
#    203,
#    455,
#    459,
#    465,
#    424,
#    486],
#   'accessibilityAttributes': {'attributes': None,
#    'showerChair': None,
#    'entranceType': None,
#    'petFriendly': '',
#    'rampAngle': 0,
#    'rampLength': 0,
#    'entranceDoorWidth': 0,
#    'roomMaxGuestsNumber': 0,
#    'distanceFromTheElevatorToTheAccessibleRoom': 0},
#   'deletedAt': None},
# ]


#Step 2 Hotel Selected
hotelId = "lp6575043f"


#Step 3 Get Room Offers
payload = {
    "hotelIds":[hotelId],
    "checkin":"2026-09-10",
    "checkout":"2026-09-12",
    "currency":"INR",
    "guestNationality":"IN",

    "occupancies":[
        {
            "adults":2
        }
    ],

    "roomMapping":True,
    "includeHotelData":True
}

r = requests.post(
    "https://api.liteapi.travel/v3.0/hotels/rates",
    headers=headers,
    json=payload
)

offers = r.json()
offers

#OUTPUT:
# {'data': [{'hotelId': 'lp6575043f',
#    'roomTypes': [{'roomTypeId': 'GY3DSLJRG4YDEMJWG43DCNL4KJDE47BSGAZDMMBZGA2DCMBQGB6DC7CSGEYTKMD4GUZDKOJQGI',
#      'offerId': '3gAWonJzkd4AEaRzcmlk2gEkRzRaVE9OQlhHVTNESU5SWkdaVERFTUJXR0UzVEFOUlJHNFpET05CV01RM0RLTlRGRzQySFlNSkRHSVlERU5SUUhFWVRBN0JTR0FaRE1NQlpHRVpIWVpMT0w1S1ZHN0NKSlo2RVNUU1NQUVpFQ01DRFBRMkRLTVJaUFJVVkFaMlZKQjZEQ05aWUdVM1RPTUpSR1EyVEFOWlRKUkZVRVdSREdFM1RBTVJSR1kzVE1NSlZFTTNETU9KTkdFM1RBTVJSR1kzVE1NSlZQUkpFTVRUNEdJWURFTlJRSEVZRElNSlFHQVlIWU1MNEtJWVRDTkpRUFEyVEVOSlpHQVpDR1VTUEVOSkVNVFJER0lZREVOUk5HQTRTMk1CVUVBWVRBT1JRR0FSUaNwcmPLQLXGj1wo9cOlb3JfcHLLAAAAAAAAAAClb3JfY23LQHO4euFHrhSiY23LQHO4euFHrhSjcGNkszIwMjYtMDktMDkgMTA6MDA6MDCicnSgo2JyZKJST6RtcmlkzgA9u82jbXJuwKNoZHDAo2ZybrVUd28tQmVkcm9vbSBBcGFydG1lbnSjc3JusFN0dWRpbyBBcGFydG1lbnSjb2NuAaRwcmtzwKNkZXTLAAAAAAAAAACiY3CCoXCShaF0szIwMjYtMDktMDQgMTA6MDA6MDChYctAtcaPXCj1w6Fjo0lOUqJ0eaZhbW91bnSidHqjR01UhaF0szIwMjYtMDktMDkgMTA6MDA6MDChYctAtcaPXCj1w6Fjo0lOUqJ0eaZhbW91bnSidHqjR01UonJ0o1JGTqRzaGlkqjE3MDIxNjc2MTWjc2lkAqNoaWSqbHA2NTc1MDQzZqNvY2ORgaFhAqNjdXKjSU5SomduoklOomNpqjIwMjYtMDktMTCiY2-qMjAyNi0wOS0xMqNnaWSgomNyy0AYAAAAAAAApHNzaWTZMHNlc3Npb25fMDE5ZmM4NDEzNzY1ajlpSjhiU01sNU9kbWNuaHBMWHdsbjE0VHl6SaNpc2jCo3NzcKCjaWZtw6VpZmNocsKjaWZywqVzZWFpZKpscDY1NzUwNDNmom5rsWxpdGVhcGlvbmJvYXJkaW5nonR4kYShacOhZLpHcmFkdWF0ZWQgdGF4IChQYXkgdG8gZ292KaFhy0B0RFHrhR64oWOjSU5SomxwwKNia3QB',
#      'supplier': 'nuitee',
#      'supplierId': 2,
#      'rates': [{'rateId': 'I42FUVCPJZBFQR2VGNCESTSSLJDVUVCEIVGUEV2HIUZVIQKOKJJEONC2IRHU4QSXJVITGRCLJZKEMRZUGJEFSTKKIRDUSWKEIVHFEUKIIVMVIQJXIJJUOQK2IRGU2QS2I5CVUSCZLJGE6TBVJNLEON2DJJFFUNSFKNKFGU2QKFNEKQ2NINCFAUJSIRFU2US2KBJFKVSBLIZFMSSCGZCEGTS2LFDVKM2UJ5GUUUSHKEZFIQKOLJKEUUSGKVCVOUSEI5CTGVCBJVJFER2ZGNKE2TKKKZCU2M2EJVHUUTSHIUZVIQKNKJJEOWJTKRGU2SSWKBJEURKNKRKDIR2JLFCEKTSSKFEEKWKEJFGUUUKHIFMUQWKNJQ2EWSKZKRBU4SSRKBITEVCFJZFFUR2BLJBUOVKTKBCU4SSFJVKFERCHJFMUIRKOKJHEOQJUKMZE2QSVIVAVSVCBJ5JFCR2BKJIXYNJVG42C4NJWPQZDAMRWFUYDSLJQHEQDCMB2GAYDUMBQPRJE67BUGA2DKNZXGN6HYVDXN4WUEZLEOJXW63JAIFYGC4TUNVSW45D4KN2HKZDJN4QEC4DBOJ2G2ZLOOR6DALRQGB6DGMJVFY2TG7D4GMYTKLRVGN6DALRQGA',
#        'occupancyNumber': 1,
#        'name': 'Studio Apartment',
#        'maxOccupancy': 2,
#        'adultCount': 2,
#        'childCount': 0,
#        'childrenAges': [],
#        'boardType': 'RO',
#        'boardName': 'Room Only',
#        'remarks': '',
#        'priceType': 'commission',
#        'commission': [{'amount': 315.53, 'currency': 'INR'}],
#        'retailRate': {'total': [{'amount': 5574.56, 'currency': 'INR'}],
#         'suggestedSellingPrice': [{'amount': 6047.869999999999,
#           'currency': 'INR',
#           'source': ''}],
#         'initialPrice': [{'amount': 5574.56, 'currency': 'INR'}],
#         'taxesAndFees': [{'included': True,
#           'description': 'Graduated tax (Pay to gov)',
#           'amount': 324.27,
#           'currency': 'INR'}]},
#        'cancellationPolicies': {'cancelPolicyInfos': [{'cancelTime': '2026-09-04 10:00:00',
#           'amount': 5574.56,
#           'currency': 'INR',
#           'type': 'amount',
#           'timezone': 'GMT'},
#          {'cancelTime': '2026-09-09 10:00:00',
#           'amount': 5574.56,
#           'currency': 'INR',
#           'type': 'amount',
#           'timezone': 'GMT'}],
#         'hotelRemarks': [],
#         'refundableTag': 'RFN'},
#        'mappedRoomId': 4045773,
#        'paymentTypes': ['NUITEE_PAY'],
#        'providerCommission': {'amount': 0, 'currency': ''},
#        'perks': [],
#        'promotions': None}],
#      'offerRetailRate': {'amount': 5574.56, 'currency': 'INR'},
#      'suggestedSellingPrice': {'amount': 6047.86,
#       'currency': 'INR',
#       'source': ''},
#      'offerInitialPrice': {'amount': 5574.56, 'currency': 'INR'},
#      'priceType': 'commission',
#      'rateType': 'package',
#      'paymentTypes': ['NUITEE_PAY']}],
#    'et': 10800}],
#  'guestLevel': 0,
#  'sandbox': True,
#  'hotels': [{'id': 'lp6575043f',
#    'name': 'Asta by Avim',
#    'main_photo': 'https://static.cupid.travel/hotels/534567675.jpg',
#    'thumbnail': 'https://static.cupid.travel/hotels/thumbnail/534567675.jpg',
#    'address': 'B Block, Areia De, opp. Riviera Palms 1, near Arpora, Arpora, Goa 403516',
#    'country_code': 'in',
#    'city_name': 'Goa',
#    'latitude': 15.560339,
#    'longitude': 73.765104,
#    'rating': 8.8,
#    'stars': 4,
#    'review_count': 27}]}


#Step 4 Get Room Images
r = requests.get(
    "https://api.liteapi.travel/v3.0/data/hotel",
    headers=headers,
    params={
        "hotelId":hotelId
    }
)

hotel = r.json()["data"]
hotel

#OUTPUT:
# {'id': 'lp6575043f',
#  'name': 'Asta by Avim',
#  'hotelDescription': "<p><strong>Luxurious Accommodation</strong><br>Experience comfort and convenience in our well-equipped guest rooms featuring modern amenities for a relaxing stay.</p><p><strong>Outdoor Swimming Pool</strong><br>Take a refreshing dip in our outdoor pool or lounge by the poolside with a drink in hand, soaking up the tropical vibes.</p><p><strong>Convenient Location</strong><br>Located just a stone's throw away from popular beaches and attractions, we offer easy access to the best of what Goa has to offer.</p><p>Book now to experience a memorable stay at Asta by Avim and make the most of your Goa getaway!</p>",
#  'hotelImportantInformation': 'This property does not accommodate bachelor(ette) or similar parties.\nA deposit may be required at the property.',
#  'checkinCheckoutTimes': {'checkin_start': '12:00 PM',
#   'checkin_end': '02:00 PM',
#   'checkout': '11:00 AM',
#   'instructions': [],
#   'special_instructions': ''},
#  'hotelImages': [{'url': 'https://static.cupid.travel/hotels/534567675.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567675.jpg',
#    'caption': 'building',
#    'order': 0,
#    'defaultImage': True},
#   {'url': 'https://static.cupid.travel/hotels/532591877.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591877.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591749.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591749.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591754.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591754.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591765.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591765.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591796.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591796.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591808.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591808.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591819.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591819.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591830.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591830.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591848.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591848.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591855.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591855.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591861.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591861.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591890.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591890.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/532591903.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/532591903.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396333.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396333.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396331.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396331.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396300.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396300.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396293.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396293.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396288.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396288.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396626.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396626.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396624.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396624.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396622.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396622.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396620.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396620.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396619.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396619.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396618.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396618.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396617.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396617.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396616.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396616.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396612.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396612.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396611.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396611.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396609.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396609.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396608.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396608.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396603.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396603.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396600.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396600.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396594.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396594.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396765.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396765.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396756.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396756.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396760.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396760.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533396763.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533396763.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/533560606.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/533560606.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567345.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567345.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567665.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567665.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567671.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567671.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567670.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567670.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567674.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567674.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567676.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567676.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567682.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567682.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/534567684.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/534567684.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False},
#   {'url': 'https://static.cupid.travel/hotels/540218017.jpg',
#    'urlHd': 'https://static.cupid.travel/hotels/540218017.jpg',
#    'caption': '',
#    'order': 0,
#    'defaultImage': False}],
#  'main_photo': 'https://static.cupid.travel/hotels/534567675.jpg',
#  'thumbnail': 'https://static.cupid.travel/hotels/thumbnail/534567675.jpg',
#  'country': 'in',
#  'city': 'Goa',
#  'starRating': 4,
#  'location': {'latitude': 15.560339, 'longitude': 73.765104},
#  'address': 'B Block, Areia De, opp. Riviera Palms 1, near Arpora, Arpora, Goa 403516',
#  'hotelFacilities': ['Offsite parking discounted rates available',
#   'Fitness facilities (surcharge)',
#   'Parking',
#   'Non-smoking rooms',
#   'Air conditioning',
#   'Room service',
#   'Family rooms',
#   'Non-smoking throughout',
#   'Guest rooms disinfected between stays',
#   'Cleaning standards that are effective against Coronavirus',
#   'Physical distancing rules followed',
#   'Cashless payment available',
#   'Contactless check-in/check-out',
#   'Mobile app for room service',
#   'Front desk (limited hours)',
#   'Free wired internet',
#   'Self parking (surcharge)',
#   'Airport transportation - pickup (surcharge)',
#   'Airport transportation - drop-off (surcharge)',
#   'Offsite parking discounted rates available',
#   'Fitness facilities (surcharge)',
#   'Internet access',
#   'Exercise/lap pool',
#   'Japanese garden',
#   'Swimming nearby',
#   'Accessible train station shuttle',
#   'No accessible train station shuttle'],
#  'zip': '403516',
#  'chain': 'Not Available',
#  'facilities': [{'facilityId': 2083,
#    'name': 'Offsite parking discounted rates available'},
#   {'facilityId': 6848, 'name': 'Fitness facilities (surcharge)'},
#   {'facilityId': 2, 'name': 'Parking'},
#   {'facilityId': 16, 'name': 'Non-smoking rooms'},
#   {'facilityId': 109, 'name': 'Air conditioning'},
#   {'facilityId': 5, 'name': 'Room service'},
#   {'facilityId': 28, 'name': 'Family rooms'},
#   {'facilityId': 108, 'name': 'Non-smoking throughout'},
#   {'facilityId': 451, 'name': 'Guest rooms disinfected between stays'},
#   {'facilityId': 449,
#    'name': 'Cleaning standards that are effective against Coronavirus'},
#   {'facilityId': 462, 'name': 'Physical distancing rules followed'},
#   {'facilityId': 461, 'name': 'Cashless payment available'},
#   {'facilityId': 460, 'name': 'Contactless check-in/check-out'},
#   {'facilityId': 463, 'name': 'Mobile app for room service'},
#   {'facilityId': 540, 'name': 'Front desk (limited hours)'},
#   {'facilityId': 584, 'name': 'Free wired internet'},
#   {'facilityId': 675, 'name': 'Self parking (surcharge)'},
#   {'facilityId': 691, 'name': 'Airport transportation - pickup (surcharge)'},
#   {'facilityId': 692, 'name': 'Airport transportation - drop-off (surcharge)'},
#   {'facilityId': 720, 'name': 'Offsite parking discounted rates available'},
#   {'facilityId': 757, 'name': 'Fitness facilities (surcharge)'},
#   {'facilityId': 761, 'name': 'Internet access'},
#   {'facilityId': 835, 'name': 'Exercise/lap pool'},
#   {'facilityId': 856, 'name': 'Japanese garden'},
#   {'facilityId': 916, 'name': 'Swimming nearby'},
#   {'facilityId': 1027, 'name': 'Accessible train station shuttle'},
#   {'facilityId': 1028, 'name': 'No accessible train station shuttle'}],
#  'rooms': [{'id': 4045774,
#    'roomName': 'Studio with Pool View',
#    'description': 'Guests will have a special experience as this studio provides a pool with a view. In the kitchen, guests will find a refrigerator, a microwave and a tea and coffee maker. The studio offers air conditioning, a mini-bar, a balcony with pool views as well as a private bathroom featuring a bath. The unit offers 1 bed.',
#    'roomSizeSquare': 25,
#    'roomSizeUnit': 'sqm',
#    'hotelId': 'lp6575043f',
#    'maxAdults': 2,
#    'maxChildren': 1,
#    'maxOccupancy': 2,
#    'bedTypes': [{'quantity': 1,
#      'bedType': 'Queen bed',
#      'bedSize': '151-180 cm wide',
#      'id': 167}],
#    'roomAmenities': [{'amenitiesId': 64,
#      'name': 'Coffee/tea maker',
#      'sort': 0},
#     {'amenitiesId': 216, 'name': 'Minibar', 'sort': 0},
#     {'amenitiesId': 312, 'name': 'Shower', 'sort': 0},
#     {'amenitiesId': 339, 'name': 'TV', 'sort': 0},
#     {'amenitiesId': 11, 'name': 'Air conditioning', 'sort': 0},
#     {'amenitiesId': 186, 'name': 'Kitchenette', 'sort': 0},
#     {'amenitiesId': 281, 'name': 'Refrigerator', 'sort': 0},
#     {'amenitiesId': 82, 'name': 'Desk', 'sort': 0},
#     {'amenitiesId': 106, 'name': 'Fan', 'sort': 0},
#     {'amenitiesId': 350, 'name': 'Toilet', 'sort': 10},
#     {'amenitiesId': 214, 'name': 'Microwave', 'sort': 0},
#     {'amenitiesId': 266, 'name': 'Private bathroom', 'sort': 0},
#     {'amenitiesId': 183, 'name': 'Kitchen', 'sort': 0},
#     {'amenitiesId': 96, 'name': 'Electric kettle', 'sort': 0},
#     {'amenitiesId': 377, 'name': 'Wardrobe or closet', 'sort': 0},
#     {'amenitiesId': 197, 'name': 'Linen', 'sort': 43},
#     {'amenitiesId': 60, 'name': 'Clothes rack', 'sort': 72},
#     {'amenitiesId': 352, 'name': 'Toilet paper', 'sort': 0},
#     {'amenitiesId': 37, 'name': 'Bottle of water', 'sort': 152},
#     {'amenitiesId': 307, 'name': 'Shampoo', 'sort': 0},
#     {'amenitiesId': 71, 'name': 'Conditioner', 'sort': 108},
#     {'amenitiesId': 35, 'name': 'Body soap', 'sort': 109},
#     {'amenitiesId': 5, 'name': 'Accessible by lift', 'sort': 29},
#     {'amenitiesId': 218, 'name': 'Mobile hotspot device', 'sort': 134}],
#    'photos': [{'url': 'https://static.cupid.travel/rooms-large-pictures/532591749.jpg',
#      'imageDescription': '',
#      'imageClass1': 'hotel room',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591749.jpg?k=b98ea102e9ee173d96bfdfee835643c48bebb41831adb29fc52fa47084a78197&o=',
#      'mainPhoto': True,
#      'score': 0,
#      'classId': 80,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591749.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591877.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591877.jpg?k=d0eaceeef227507273aaf3971623df1a4cc42f6717d5f922b4bc448592dd25f0&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591877.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591861.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591861.jpg?k=96beecd51f0143460b658cba7d97f0cc32489553485a06e0a4cf00747e1ffd2f&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591861.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591848.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591848.jpg?k=6de7c783fd619b81dc3c270fd8564ef545f59e87b728ca7383090d164e17bcb9&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591848.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591808.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591808.jpg?k=50d41c9289f37f1cc3b40597893b87d212917e931fbe57155fc0fd13e82d0d8a&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591808.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591796.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591796.jpg?k=8d99db15432c708f13fa7080a2526615caadecbaebad244a5caad911030de330&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591796.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591765.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591765.jpg?k=0263a695117c7deba6222b87fa21eccbde929cf63745a23334f4d50510060302&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591765.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591890.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591890.jpg?k=4dcd6454681338ab2aa65388690a71201ef9053c93456ddc2e1ac21a0bdf3e73&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591890.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/532591903.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/532591903.jpg?k=ed2fed11b0e43790c22ed5e5bb0290ec50eab1449da421747972cae70993b3ac&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/532591903.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396300.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396300.jpg?k=40882eb2e757f5d58d1636b2a5211468881dce6bb6b636e703704c24f650c172&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396300.jpg'}],
#    'views': [{'view': 'Pool View', 'id': 2}],
#    'bedRelation': 'NONE'},
#   {'id': 4045775,
#    'roomName': 'Superior Apartment',
#    'description': "This apartment's special feature is the pool with a view. This apartment consists of 1 living room, 1 separate bedroom and 1 bathroom with a bath and free toiletries. Meals can be prepared in the kitchen, which is equipped with a refrigerator, a microwave and a tea and coffee maker. Featuring a balcony with pool views, this apartment also provides air conditioning and a flat-screen TV. The unit offers 2 beds.",
#    'roomSizeSquare': 35,
#    'roomSizeUnit': 'sqm',
#    'hotelId': 'lp6575043f',
#    'maxAdults': 3,
#    'maxChildren': 3,
#    'maxOccupancy': 4,
#    'bedTypes': [{'quantity': 1,
#      'bedType': 'Extra-large double bed (Super-king size)',
#      'bedSize': '181-210 cm wide',
#      'id': 39}],
#    'roomAmenities': [{'amenitiesId': 64,
#      'name': 'Coffee/tea maker',
#      'sort': 0},
#     {'amenitiesId': 216, 'name': 'Minibar', 'sort': 0},
#     {'amenitiesId': 312, 'name': 'Shower', 'sort': 0},
#     {'amenitiesId': 339, 'name': 'TV', 'sort': 0},
#     {'amenitiesId': 11, 'name': 'Air conditioning', 'sort': 0},
#     {'amenitiesId': 186, 'name': 'Kitchenette', 'sort': 0},
#     {'amenitiesId': 281, 'name': 'Refrigerator', 'sort': 0},
#     {'amenitiesId': 82, 'name': 'Desk', 'sort': 0},
#     {'amenitiesId': 298, 'name': 'Seating Area', 'sort': 59},
#     {'amenitiesId': 106, 'name': 'Fan', 'sort': 0},
#     {'amenitiesId': 350, 'name': 'Toilet', 'sort': 10},
#     {'amenitiesId': 214, 'name': 'Microwave', 'sort': 0},
#     {'amenitiesId': 266, 'name': 'Private bathroom', 'sort': 0},
#     {'amenitiesId': 183, 'name': 'Kitchen', 'sort': 0},
#     {'amenitiesId': 96, 'name': 'Electric kettle', 'sort': 0},
#     {'amenitiesId': 377, 'name': 'Wardrobe or closet', 'sort': 0},
#     {'amenitiesId': 197, 'name': 'Linen', 'sort': 43},
#     {'amenitiesId': 60, 'name': 'Clothes rack', 'sort': 72},
#     {'amenitiesId': 352, 'name': 'Toilet paper', 'sort': 0},
#     {'amenitiesId': 37, 'name': 'Bottle of water', 'sort': 152},
#     {'amenitiesId': 307, 'name': 'Shampoo', 'sort': 0},
#     {'amenitiesId': 71, 'name': 'Conditioner', 'sort': 108},
#     {'amenitiesId': 35, 'name': 'Body soap', 'sort': 109},
#     {'amenitiesId': 5, 'name': 'Accessible by lift', 'sort': 29},
#     {'amenitiesId': 218, 'name': 'Mobile hotspot device', 'sort': 134}],
#    'photos': [{'url': 'https://static.cupid.travel/rooms-large-pictures/533396594.jpg',
#      'imageDescription': '',
#      'imageClass1': 'hotel room',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396594.jpg?k=d3bd501030268e41b9441bd899d990fcb02ee84f932e3fab83c38077d3c2b5e2&o=',
#      'mainPhoto': True,
#      'score': 0,
#      'classId': 80,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396594.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396626.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396626.jpg?k=17b0f2c0aa6eecf5880bae295d5919474b6951937bd7c2759da1bf467bfd8d42&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396626.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396624.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396624.jpg?k=d2caf4d66e80cfff6a9ffa9b2585ca12fc26001e94fe4181f11e76be8dfed6a5&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396624.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396622.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396622.jpg?k=bcb9f15e764990d02b5e3392c140aeda74bbefb9ef84043205f913e3e3ddebd7&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396622.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396620.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396620.jpg?k=33b367f45d52883ab14ec6ee87cbc4e623d8bd6665a747ee73cf2784748c8f2b&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396620.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396619.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396619.jpg?k=4406dab27bc35a0f9738141ba6312577fed846f6e8f20abbf337661ad348218c&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396619.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396618.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396618.jpg?k=ed673ed300f32346f53c19cc375bc7f6b9d99ae5ce73520d20afd1be0ee1c8fc&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396618.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396617.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396617.jpg?k=f1ecc99cd755b6f36fd76d93bca460e8fa5f79d1742af96b24c35bcd92cf74ab&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396617.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396616.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396616.jpg?k=14f9172f3a3d258e886ce2217bc9aa4a81a6a845a21e5e1129b0b2af432a27f1&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396616.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396612.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396612.jpg?k=adafeabb15a858c5b10d2933acb7190f2ca5fee8ac479db35d58f5f8833dad8a&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396612.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396611.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396611.jpg?k=8b3896c9611ba41669715ae48de86e1ae334fac63b5ff782f23a51ebb16382e7&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396611.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396609.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396609.jpg?k=c4c81e1f7b5e371b6ab2fdad8e61f1b3f972d6bd5351cb6dd28d2a65f20acf15&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396609.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396608.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396608.jpg?k=1c0df6d2db97563b5a5102e3d04800749eafcbff94032403319a042ef95210a2&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396608.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396603.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396603.jpg?k=8999c67b8c9e1add4124b7c92241c1b8753a1271808a9b418007a3e3f51db266&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396603.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396600.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396600.jpg?k=fe53eb504b405186e01c2350589db8bb3f66713e6e8f0217b6633dd919ff4db9&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396600.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396300.jpg',
#      'imageDescription': '',
#      'imageClass1': 'bathroom',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396300.jpg?k=40882eb2e757f5d58d1636b2a5211468881dce6bb6b636e703704c24f650c172&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 26,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396300.jpg'}],
#    'views': [{'view': 'Pool View', 'id': 2}],
#    'bedRelation': 'NONE'},
#   {'id': 4045773,
#    'roomName': 'Two-Bedroom Apartment',
#    'description': 'This apartment provides a pool with a view. This apartment includes 1 living room, 2 separate bedrooms and 2 bathrooms with a bath and free toiletries. Guests can make meals in the kitchen that has a refrigerator, a microwave and a tea and coffee maker. Boasting a balcony with pool views, this apartment also offers air conditioning and a flat-screen TV. The unit has 4 beds.',
#    'roomSizeSquare': 50,
#    'roomSizeUnit': 'sqm',
#    'hotelId': 'lp6575043f',
#    'maxAdults': 6,
#    'maxChildren': 5,
#    'maxOccupancy': 6,
#    'bedTypes': [{'quantity': 2,
#      'bedType': 'Sofa bed',
#      'bedSize': 'Variable Size',
#      'id': 38}],
#    'roomAmenities': [{'amenitiesId': 64,
#      'name': 'Coffee/tea maker',
#      'sort': 0},
#     {'amenitiesId': 216, 'name': 'Minibar', 'sort': 0},
#     {'amenitiesId': 312, 'name': 'Shower', 'sort': 0},
#     {'amenitiesId': 339, 'name': 'TV', 'sort': 0},
#     {'amenitiesId': 11, 'name': 'Air conditioning', 'sort': 0},
#     {'amenitiesId': 186, 'name': 'Kitchenette', 'sort': 0},
#     {'amenitiesId': 281, 'name': 'Refrigerator', 'sort': 0},
#     {'amenitiesId': 82, 'name': 'Desk', 'sort': 0},
#     {'amenitiesId': 298, 'name': 'Seating Area', 'sort': 59},
#     {'amenitiesId': 106, 'name': 'Fan', 'sort': 0},
#     {'amenitiesId': 350, 'name': 'Toilet', 'sort': 10},
#     {'amenitiesId': 214, 'name': 'Microwave', 'sort': 0},
#     {'amenitiesId': 266, 'name': 'Private bathroom', 'sort': 0},
#     {'amenitiesId': 183, 'name': 'Kitchen', 'sort': 0},
#     {'amenitiesId': 10, 'name': 'Additional toilet', 'sort': 103},
#     {'amenitiesId': 96, 'name': 'Electric kettle', 'sort': 0},
#     {'amenitiesId': 377, 'name': 'Wardrobe or closet', 'sort': 0},
#     {'amenitiesId': 197, 'name': 'Linen', 'sort': 43},
#     {'amenitiesId': 100,
#      'name': 'Entire unit located on ground floor',
#      'sort': 165},
#     {'amenitiesId': 60, 'name': 'Clothes rack', 'sort': 72},
#     {'amenitiesId': 352, 'name': 'Toilet paper', 'sort': 0},
#     {'amenitiesId': 37, 'name': 'Bottle of water', 'sort': 152},
#     {'amenitiesId': 307, 'name': 'Shampoo', 'sort': 0},
#     {'amenitiesId': 71, 'name': 'Conditioner', 'sort': 108},
#     {'amenitiesId': 35, 'name': 'Body soap', 'sort': 109},
#     {'amenitiesId': 5, 'name': 'Accessible by lift', 'sort': 29},
#     {'amenitiesId': 218, 'name': 'Mobile hotspot device', 'sort': 134}],
#    'photos': [{'url': 'https://static.cupid.travel/rooms-large-pictures/533396765.jpg',
#      'imageDescription': '',
#      'imageClass1': 'hotel room',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396765.jpg?k=891f87ec9c95c1dd5dbd8cee2b94143a4a77308b8f1f4f2fc7554f287e6c4b84&o=',
#      'mainPhoto': True,
#      'score': 0,
#      'classId': 80,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396765.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533560606.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533560606.jpg?k=5ed749567773458074a7c1fc5c285286d2558887e0d1f1f797e20136a92463d9&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533560606.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396331.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396331.jpg?k=207138cc9dca5cdbbefdab77947fff4aa674a052d75585de21f727e27d0afe8c&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396331.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396756.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396756.jpg?k=c1de57f7e07e531d8f2488089c9281b9692b975e3ae7593df3aca9dc1184dba1&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396756.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396760.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396760.jpg?k=38d6eaa695a250083d65e64f89e79b91b76ebd138b868520cda74d21cb42912c&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396760.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396763.jpg',
#      'imageDescription': '',
#      'imageClass1': '',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396763.jpg?k=13ca6e5802515c982414e1aea11a42c084cef3acecc87b0d192533bc0736a48c&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 0,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396763.jpg'},
#     {'url': 'https://static.cupid.travel/rooms-large-pictures/533396300.jpg',
#      'imageDescription': '',
#      'imageClass1': 'bathroom',
#      'imageClass2': '',
#      'failoverPhoto': 'https://q-xx.bstatic.com/xdata/images/hotel/max1200/533396300.jpg?k=40882eb2e757f5d58d1636b2a5211468881dce6bb6b636e703704c24f650c172&o=',
#      'mainPhoto': False,
#      'score': 0,
#      'classId': 26,
#      'classOrder': 0,
#      'hd_url': 'https://static.cupid.travel/rooms-large-pictures/533396300.jpg'}],
#    'views': [{'view': 'Pool View', 'id': 2}],
#    'bedRelation': 'NONE'}],
#  'phone': '',
#  'fax': '',
#  'email': '',
#  'hotelType': 'Hotels',
#  'hotelTypeId': 204,
#  'airportCode': '',
#  'rating': 8.8,
#  'reviewCount': 27,
#  'parking': '',
#  'groupRoomMin': 0,
#  'childAllowed': False,
#  'petsAllowed': False,
#  'policies': [],
#  'rohId': 4045774,
#  'sentiment_analysis': {'cons': ['Some rooms with mould',
#    'Mixed opinions on location'],
#   'pros': ['Clean rooms', 'Friendly staff', 'Spacious rooms'],
#   'categories': [{'name': 'Cleanliness',
#     'rating': 8,
#     'description': 'Guests appreciated the overall cleanliness of the hotel.'},
#    {'name': 'Service',
#     'rating': 8,
#     'description': 'Staff were described as friendly and helpful by most guests.'},
#    {'name': 'Location',
#     'rating': 7.5,
#     'description': 'Some guests found the location convenient, while others felt it was a bit far from certain attractions.'},
#    {'name': 'Room Quality',
#     'rating': 7.7,
#     'description': 'Spacious rooms were generally well-received, although a few guests mentioned minor issues like mould.'},
#    {'name': 'Amenities',
#     'rating': 7.2,
#     'description': 'Mixed feedback on amenities, with some guests enjoying the space and others wishing for more.'},
#    {'name': 'Value for Money',
#     'rating': 6.9,
#     'description': 'Opinions varied on whether the price matched the offering, with some finding it affordable and others too high.'},
#    {'name': 'Food and Beverage',
#     'rating': 7.3,
#     'description': 'Overall positive feedback on food and beverage options, though some suggested improvements in variety.'},
#    {'name': 'Overall Experience',
#     'rating': 8,
#     'description': 'Most guests had a positive experience and would recommend the hotel to others.'}]},
#  'sentiment_updated_at': '2025-08-01T15:04:18Z',
#  'deletedAt': None}

